javac -encoding UTF8 ChoixFinal.java
javac -encoding UTF8 Femme.java
javac -encoding UTF8 FenetreChoixRecette.java
javac -encoding UTF8 Gestion.java
javac -encoding UTF8 Homme.java
javac -encoding UTF8 Informations.java
javac -encoding UTF8 LecteurHtml.java
javac -encoding UTF8 nonBinaire.java
javac -encoding UTF8 Recette.java
javac -encoding UTF8 Refrigerateur.java
javac -encoding UTF8 Users.java
javac -encoding UTF8 Fenetre.java